Repository 2pisoftware/cmfive-boilerplate, pull requests merged in 2021-03, with the labels that each got.

#27 feat: semantic pull requests
  .github/pull_request_template.md
  .github/semantic.yml
  .github/workflows/ci.yml
Labels: enhancement

#28 feat: develop
  .github/pull_request_template.md
  .github/semantic.yml
  .github/workflows/ci.yml
  cmfiveTests.php
Labels: enhancement

#30 fix: nginx config
  .build/common/nginx/default.conf.template
  nginx.conf
Labels: bug, enhancement

#35 feat: develop
  .build/environment/dev/configs/cmfive/config.php.template
Labels: enhancement

#36 fix: updated ci action
  .github/pull_request_template.md
  .github/workflows/ci.yml
Labels: bug
