Repository 2pisoftware/cmfive-boilerplate, pull requests merged in 2024-02, with the labels that each got.

#89 Create dependabot.yml
  .github/dependabot.yml
Labels: dependencies, awaiting-review

#99 Remove unused glob-fs test dependency
  test/playwright/package-lock.json
  test/playwright/package.json
Labels: dependencies, awaiting-review

#102 chore(ci): Sync dependabot and update CI
  .github/dependabot.yml
  .github/workflows/ci.yml
Labels: enhancement, dependencies, awaiting-review, github_actions

#109 Update README.md
  README.md
Labels: enhancement

#115 Docker tweaks
  .codepipeline/docker/Dockerfile
  .codepipeline/docker/README.md
  .codepipeline/docker/configs/supervisord/supervisord.conf
  .codepipeline/docker/setup.sh
  docker-compose.yml
  index.php
Labels: enhancement

#118 Update ci.yml
  .github/workflows/ci.yml
Labels: enhancement, github_actions

#117 Update docker-image.yml
  .github/workflows/docker-image.yml
Labels: enhancement
